sonar.organization=nelsonmeier
sonar.projectKey=NelsonMeier_sopra-fs26-group-34-server

# relative paths to source directories. More details and properties are described
# at https://docs.sonarsource.com/sonarqube-cloud/advanced-setup/analysis-scope/
sonar.sources=./app